# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.8.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/hiroba-news-backend: 11e74b78c09edb59d486d7e48ed48f15973a3748b74f03ede25e9ded6f86bc19
  creationTimestamp: "2026-04-14T11:56:18Z"
  labels:
    app: hiroba-news
  name: hiroba-news
spec:
  containers:
  - env: []
    image: ghcr.io/kanikama0601/hiroba-news-smart-monitor:release
    name: hiroba-news-backend
    ports:
    - containerPort: 8888
      hostPort: 8888
    tty: true

